// The Starlight project's Astro configuration. Static on purpose: the
// per-repo data (the site's title and the sidebar) is generated by
// madarch into src/generated/site.mjs, which this file imports — so the
// template stays byte-stable and only generated data moves per build.
// The wiki's stylesheet and its diagram module ship with every page
// (head), and the LikeC4 web component and the Mermaid runtime the build
// copies into public/assets/ are plain static files served from the root.
// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { site } from './src/generated/site.mjs';

export default defineConfig({
  outDir: 'site',
  integrations: [
    starlight({
      title: site.title,
      sidebar: site.sidebar,
      customCss: ['./src/styles/wiki.css'],
      head: [
        { tag: 'script', attrs: { type: 'module', src: '/assets/likec4-view.js' }, content: '' },
        { tag: 'script', attrs: { type: 'module', src: '/wiki-diagram.mjs' }, content: '' },
      ],
    }),
  ],
});
