/**
 * The Zensical engine's writer: turns the engine-neutral pages
 * (src/wiki/pages.ts) into a Zensical project — one Markdown file per page
 * under `docs/` and a `zensical.toml` with the site's name and navigation.
 * A page link is written by page id and leaves this writer as a relative
 * path into the page's own file; the built site itself is produced by
 * `uvx zensical==0.0.66 build`, which the caller runs in the project
 * folder afterwards. Deterministic: the same pages and site name give the
 * same bytes, with no clock and no locale anywhere.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import type { WikiCell, WikiPage } from './pages.js';

/** The folder a prefixed page id lives in, one level under `docs/`. */
const FOLDER_BY_PREFIX: Record<string, string> = { domain: 'domains' };

/**
 * The project-relative file a page id is written to: `home` is the site's
 * index, `domain/<id>` lands at `domains/<id>.md`. Throws for an id this
 * writer has no folder for, so a new page kind cannot silently build into
 * the wrong place.
 */
export function pagePath(id: string): string {
  if (id === 'home') return 'index.md';
  const slash = id.indexOf('/');
  if (slash < 0) throw new Error(`page id "${id}" has no kind prefix: expected "home" or "<kind>/<id>"`);
  const folder = FOLDER_BY_PREFIX[id.slice(0, slash)];
  if (folder === undefined) throw new Error(`page id "${id}" names an unknown kind: no folder is mapped for "${id.slice(0, slash)}"`);
  return `${folder}/${id.slice(slash + 1)}.md`;
}

/**
 * Text in Markdown output: the characters Markdown reads as markup
 * escaped, control characters (a table cell's newline included) as
 * spaces — the same rule `src/render/mermaid.ts` writes its pages by.
 */
function markdownText(text: string): string {
  return text.replace(/[\u0000-\u001f\u007f]/g, ' ').replace(/[\\`*_[\]<>|]/g, '\\$&');
}

/** A TOML basic string: backslash and quote escaped, nothing else. */
function tomlString(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

/** The link a table cell leaves as, relative to the page holding it. */
function linkCell(cell: Extract<WikiCell, { page: string }>, fromPath: string): string {
  return `[${markdownText(cell.text)}](${relative(dirname(fromPath), pagePath(cell.page))})`;
}

function renderCell(cell: WikiCell, fromPath: string): string {
  return typeof cell === 'string' ? markdownText(cell) : linkCell(cell, fromPath);
}

/** One page's Markdown: its title as the heading, then every block. */
function renderPage(page: WikiPage, knownIds: ReadonlySet<string>): string {
  const fromPath = pagePath(page.id);
  const chunks: string[] = [];
  for (const block of page.blocks) {
    if (block.kind === 'heading') {
      chunks.push(`${'#'.repeat(block.level)} ${markdownText(block.text)}`);
    } else if (block.kind === 'paragraph') {
      chunks.push(markdownText(block.text));
    } else {
      for (const row of block.rows) {
        for (const cell of row) {
          if (typeof cell !== 'string' && !knownIds.has(cell.page)) {
            throw new Error(`page "${page.id}" links to "${cell.page}", which is not a page of this wiki: add the page or fix the link`);
          }
        }
      }
      chunks.push(
        [
          `| ${block.columns.map(markdownText).join(' | ')} |`,
          `| ${block.columns.map(() => '---').join(' | ')} |`,
          ...block.rows.map((row) => `| ${row.map((cell) => renderCell(cell, fromPath)).join(' | ')} |`),
        ].join('\n'),
      );
    }
  }
  const head = `# ${markdownText(page.title)}`;
  return chunks.length === 0 ? `${head}\n` : `${head}\n\n${chunks.join('\n\n')}\n`;
}

/**
 * The navigation from the pages' `nav` places: the home page first, then
 * one section per first nav segment in page order, each entry the page's
 * title naming its file.
 */
function navToml(pages: readonly WikiPage[]): string {
  const sections = new Map<string, WikiPage[]>();
  for (const page of pages) {
    if (page.id === 'home') continue;
    const section = page.nav[0] ?? page.title;
    const group = sections.get(section) ?? [];
    group.push(page);
    sections.set(section, group);
  }
  const parts = [`{ ${tomlString('Home')} = ${tomlString(pagePath('home'))} }`];
  for (const [section, group] of sections) {
    const children = group.map((page) => `{ ${tomlString(page.title)} = ${tomlString(pagePath(page.id))} }`).join(', ');
    parts.push(`{ ${tomlString(section)} = [${children}] }`);
  }
  return `nav = [${parts.join(', ')}]`;
}

function zensicalToml(pages: readonly WikiPage[], siteName: string): string {
  return [
    '# Generated by madarch (scripts/wiki.ts) — edit the generator, not this file.',
    '[project]',
    `site_name = ${tomlString(siteName)}`,
    navToml(pages),
    '',
    '[project.theme]',
    'language = "en"',
    '',
    '[[project.theme.palette]]',
    'media = "(prefers-color-scheme: light)"',
    'scheme = "default"',
    'toggle.icon = "lucide/sun"',
    'toggle.name = "Switch to dark mode"',
    '',
    '[[project.theme.palette]]',
    'media = "(prefers-color-scheme: dark)"',
    'scheme = "slate"',
    'toggle.icon = "lucide/moon"',
    'toggle.name = "Switch to light mode"',
    '',
  ].join('\n');
}

export interface ZensicalSiteOptions {
  /** The site's name, as `zensical.toml`'s `site_name`. */
  readonly siteName: string;
}

/**
 * Writes the Zensical project for `pages` into `projectDir` (created):
 * `docs/<page path>.md` for every page and `zensical.toml` beside it.
 * Throws when a link names a page the set does not hold — a broken link
 * never reaches the engine.
 */
export function writeZensicalProject(pages: readonly WikiPage[], projectDir: string, options: ZensicalSiteOptions): void {
  const knownIds = new Set(pages.map((page) => page.id));
  for (const page of pages) {
    const file = join(projectDir, 'docs', pagePath(page.id));
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, renderPage(page, knownIds));
  }
  writeFileSync(join(projectDir, 'zensical.toml'), zensicalToml(pages, options.siteName));
}
