/**
 * The Zensical engine's writer: turns the engine-neutral pages into a
 * Zensical project — `docs/<page path>.md` per page, `zensical.toml` beside
 * them with the navigation, and the diagram tabs' stylesheet and module —
 * which `uvx zensical==… build` turns into the site. The pages' bodies come
 * from the shared render module; what Zensical owns here is the project's
 * shape: the TOML, the file layout and the link spellings (relative `.md`
 * paths, the engine's own heading slugs). The repository's documents are
 * pages of the same layout, their Markdown written whole with the shared
 * rewriter's links.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { isDocumentPage, type AnyWikiPage } from './pages.js';
import { pagePath } from './pages-path.js';
import { diagramModuleJs, navTree, preparePages, renderDocumentBody, renderPageBody, TABS_CSS, type NavEntry, type NavSection, type WriterLinks, type WikiRenderOptions } from './render.js';

/** A TOML basic string: backslash and quote escaped, nothing else. */
function tomlString(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

/**
 * The heading id a Zensical page carries for a heading's text: lowercased,
 * punctuation dropped, whitespace and dash runs dashed — the slug rule the
 * engine's Markdown reader applies, so a `#` link lands on it.
 */
function headingId(text: string): string {
  return text
    .normalize('NFKC')
    .toLowerCase()
    .replace(/[^\p{L}\p{N}_\s-]/gu, '')
    .trim()
    .replace(/[-_\s]+/g, '-');
}

/** Where a Zensical link points: from the page's file to the target page's file. */
const zensicalLinks: WriterLinks = {
  pathOf(pageId: string, context): string {
    return relative(dirname(context.fromPath), pagePath(pageId));
  },
  slugOf: headingId,
};

export interface ZensicalSiteOptions extends WikiRenderOptions {
  /** The site's name, as `zensical.toml`'s `site_name`. */
  readonly siteName: string;
}

function navEntryToml(entry: NavEntry): string {
  if ('path' in entry) return `{ ${tomlString(entry.title)} = ${tomlString(entry.path)} }`;
  return `{ ${tomlString(entry.title)} = [${entry.children.map(navEntryToml).join(', ')}] }`;
}

/** The navigation in `zensical.toml`'s shape: the home page first, then one group per section. */
function navToml(sections: readonly NavSection[]): string {
  const parts = [`{ ${tomlString('Home')} = ${tomlString(pagePath('home'))} }`];
  for (const section of sections) {
    parts.push(`{ ${tomlString(section.title)} = [${section.entries.map(navEntryToml).join(', ')}] }`);
  }
  return `nav = [${parts.join(', ')}]`;
}

function zensicalToml(pages: readonly AnyWikiPage[], siteName: string): string {
  return [
    '# Generated by madarch (scripts/wiki.ts) — edit the generator, not this file.',
    '[project]',
    `site_name = ${tomlString(siteName)}`,
    navToml(navTree(pages)),
    // The diagram tabs' wiring: the stylesheet the writer emits, the LikeC4
    // web component and the Mermaid runtime the build ships beside it.
    'extra_css = ["stylesheets/wiki.css"]',
    'extra_javascript = [{ path = "assets/likec4-view.js", type = "module" }, { path = "javascripts/wiki-diagram.mjs", type = "module" }]',
    '',
    '[project.theme]',
    'language = "en"',
    '',
    '[[project.theme.palette]]',
    'media = "(prefers-color-scheme: light)"',
    'scheme = "default"',
    'toggle.icon = "lucide/sun"',
    'toggle.name = "Switch to dark mode"',
    '',
    '[[project.theme.palette]]',
    'media = "(prefers-color-scheme: dark)"',
    'scheme = "slate"',
    'toggle.icon = "lucide/moon"',
    'toggle.name = "Switch to light mode"',
    '',
  ].join('\n');
}

/**
 * The stylesheet's Zensical own head: the banner and the rule that makes
 * the engine's content area (`.md-content`) the container the LikeC4
 * panel breaks out to. The tab rules shared by both engines follow.
 */
const ZENSICAL_CSS_HEAD: readonly string[] = [
  '/* Generated by madarch (scripts/wiki.ts) — edit the generator, not this file. */',
  '/* The LikeC4 panel is framed by the content area of the page (the',
  '   .md-content of the engine), not by the text column: it breaks out to',
  '   exactly the content area, centred, so the view stays on the page at',
  '   any width and the fitted diagram scales as large as that area allows —',
  '   the larger the box, the larger the labels. The container query',
  '   measures the content area wherever the engine puts it; without it the',
  '   panel simply fills the text column. Comments here are CSS block',
  '   comments: a // line is not a comment in CSS, and the parser eats the',
  '   rule after it. */',
  '.md-content {',
  '  container-type: inline-size;',
  '}',
];

/** Where the diagram tabs' module finds the Mermaid runtime the build ships. */
const MERMAID_IMPORT = '../assets/mermaid/mermaid.esm.min.mjs';

/**
 * Writes the Zensical project for `pages` into `projectDir` (created):
 * `docs/<page path>.md` for every page — the model pages rendered from
 * their blocks, the repository's documents from their own Markdown, links
 * rewritten — plus `zensical.toml` and the diagram tabs' stylesheet and
 * module under `docs/`. The LikeC4 web component, the Mermaid runtime and
 * the documents' images are the build's to ship. Throws when a link names a
 * page or a heading the set does not hold, or a diagram block names a view
 * the diagrams map does not — a broken page never reaches the engine.
 */
export function writeZensicalProject(pages: readonly AnyWikiPage[], projectDir: string, options: ZensicalSiteOptions): void {
  const prepared = preparePages(pages);
  for (const page of pages) {
    const file = join(projectDir, 'docs', pagePath(page.id));
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, isDocumentPage(page) ? renderDocumentBody(page, zensicalLinks) : renderPageBody(page, options, prepared, zensicalLinks));
  }
  mkdirSync(join(projectDir, 'docs', 'stylesheets'), { recursive: true });
  mkdirSync(join(projectDir, 'docs', 'javascripts'), { recursive: true });
  writeFileSync(join(projectDir, 'docs', 'stylesheets', 'wiki.css'), [...ZENSICAL_CSS_HEAD, ...TABS_CSS].join('\n'));
  writeFileSync(join(projectDir, 'docs', 'javascripts', 'wiki-diagram.mjs'), diagramModuleJs(MERMAID_IMPORT));
  writeFileSync(join(projectDir, 'zensical.toml'), zensicalToml(pages, options.siteName));
}
